# Name of your Slack (Deprecated in favour of the slack_name env var)
slack_name: efectotequila

# Name of environment variable that determines if destalinator should
# actually do things to a live slack. Without this environment variable,
# everything will output in a "dry run" fashion (debug messages should take place,
# but no changes or messages should affect a live Slack).
activated: false

# What should the bot's name be when it posts?
bot_name: "Archivaldo"

# What should the bot's avatar be when it posts?
bot_avatar_url: "https://i.imgur.com/nXn77zC.png"

# Days of silence before we warn a channel it's going to be archived
warn_threshold: 30

# Days of silence before we auto-archive a channel
archive_threshold: 60

# Where should we post "general" announcement messages?
general_message_channel: "canales-inactivos"

# Where should we announce new channels?
announce_channel: "canales-nuevos"

# Where do we send control messages?
control_channel: "archivaldo-control"

# Where to send destalinator debug logs
log_channel: "archivaldo-log"

# Channels to ignore when archiving (i.e. they can be silent and not get archived)
ignore_channels:
  - archivaldo-log
  - canales-inactivos
  - canales-nuevos
  - archivaldo-control
  - askanything 
  - asktech 
  - deportv 
  - gas_tronomico 
  - kheverga 
  - motivate 
  - nocontext 
  - nosvaleverga 
  - nsfl 
  - spanishnt 
  - til 
  - tuitazos 
  - tvnotas 
  - viejitoenojado 
  - visto_en_fb 
  - yacallatepincherafa 
  - salebai

# Regular expression patterns for additional channels to ignore during archiving
ignore_channel_patterns:
  - ^zmeta-
  - lacantina
  - buenavibra
  - general
  - nba
  - oled
  - pochos

# Users to ignore when considering if a channel is stale
ignore_users:
  - Slackbot
  - Archivaldo
  - Alvaritobot
  - archivaldo

# Which message subtypes count as activity?
# "None" means the message was typed by a human and is included by default.
included_subtypes:
  - bot_message
  - channel_name
  - channel_purpose
  - channel_topic
  - file_mention
  - file_share
  - me_message
  - message_replied
  - reply_broadcast
  - slackbot_response

# When should destalinator run?
schedule_hour: 4
